### PR TITLE
[OSC-28] 🖊️ Add COps framework

### PR DESCRIPTION
**Pull request by lucasjohnston**
This commit adds the COps framework, as well as making some minor code and style edits.

### CODE REVIEW

**Comment by emmanorthcott** [comment]
Could we change the emoji for Knowledge and Impact to something friendlier? We could use the brain that we use for knowledge in the other frameworks.

**Comment by lucasjohnston** [comment]
🕐 Waiting for approval from @bethmonzo before merge is completed

**Comment by lucasjohnston** [comment]
> 🕐 Waiting for approval from @bethmonzo before merge is completed

Have received feedback from Beth. Changes to be made:
-> All content within sublevels dropdown (duplication rather than shared text at the top)
-> Ideally add images to the framework site

**Comment by emmanorthcott** [comment]
On the comment of adding the visuals I had a similar conversation with Will on whether we could turn the "To view a framework, please select a level above" page into a customisable page for teams to give context on their frameworks. This could be the solution to Beth's request. I think doing something basic with .md would work.

**Comment by lucasjohnston** [comment]
> ...turn the "To view a framework, please select a level above" page into a customisable page for teams to give context on their frameworks. This could be the solution to Beth's request. I think doing something basic with .md would work.
This would be pretty simple to implement, am totally up for that!

**Pull request closed without merging**
